apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-demo
  template:
    metadata:
      labels:
        app: cpu-demo
    spec:
      containers:
      - name: cpu-demo
        image: vish/stress
        args:
        - -cpus
        - "1"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
